文件选择区:
  图片文件夹: images/12_13/9
  掩膜文件: maskfile.csv
  平面照明光斑图: temp/2024-01-04-20-46-46-imgs.bmp
模式选择区: 
  掩膜导入: 新生成掩膜
  掩膜生成方法: 预先法
  掩膜图片编号: 1
  掩膜图片数量: 2
  阈值分割方法: 普通阈值分割
  设定阈值: 70
  数据模式: 单组数据
  浏览图片组序: 1
  浏览图片图序: 1
三维形貌生成:
  轴向包络提取方法: 质心法
  扫描步进: 0.1
  缩放系数: 0.05
  插值方法: 不插值
视场大小:
  放大倍数: 60
  相机像元尺寸: 3.45
  相机分辨力w: 2448
  相机分辨力h: 2048
DMD设置:
  DMD读取帧率设置: 24Hz
  DMD读取帧率: 24
  DMD参数设置模式: 自行调试参数
  显示图样数: 9
  预留PZT移动时间: 18
图案设置:
  图案模式选择: 点阵阵列
  图案宽度: 3
  图案周期: 3
  图案数量: 9
  图案编号: 1
  图案x坐标: 1
  图案y坐标: 1
相机设置:
  相机曝光时间: 1
  相机帧率: 30
  相机增益: 3
  ROI原点x坐标: 0
  ROI原点y坐标: 0
  ROI宽度: 1240
  ROI高度: 600
采集设置:
  光源强度: 20
  扫描层数: 24
  pzt位置: 100
  扫描步进: 100
  


